name: non-regression tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mac:
    strategy:
      matrix:
        arch: [x86_64, arm64]
        printf: [fmtdbg, normal]
        include:
          - printf: fmtdbg
            debugprintf: --with-debug-printf-format
          - arch: x86_64
            runs-on: macos-15-intel
          - arch: arm64
            runs-on: macos-15
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: install prerequisites
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: brew install flock gdk-pixbuf dylibbundler create-dmg # glib => already installed
    - name: configure
      run: |
          set +x
          ./configure ${{ matrix.debugprintf }} --with-werror
    - name: make
      run: |
        cat Makefile.config
        make -j$(sysctl -n hw.ncpu || echo 2)
    - name: check executable
      run: |
          ./dvdisaster --version
          ./dvdisaster --version | grep "dvdisaster Light"
    - name: prepare dist
      run: ./.github/workflows/make-mac-app.sh ${{ github.ref }} ${{ matrix.arch }}
    - name: regression tests
      if: matrix.printf == 'normal'
      env:
        REGTEST_NO_UTF8: 1
        MAX_JOBS: 4
      run: |
        mkdir -p /var/tmp/regtest
        echo "Number of available processors: $(sysctl -n hw.ncpu || echo U)"
        ./regtest/runtests.sh

  win:
    runs-on: windows-latest
    strategy:
      matrix:
        printf: [fmtdbg, normal]
        include:
          - printf: fmtdbg
            debugprintf: --with-debug-printf-format
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: git diffutils make pkg-config mingw-w64-x86_64-glib2 mingw-w64-x86_64-gcc mingw-w64-x86_64-ntldd-git man zip
    - name: git config
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: configure
      run: ./configure ${{ matrix.debugprintf }} --with-werror
    - name: make
      run: nproc && make -j$(nproc)
    - name: check executable
      run: |
          ./dvdisaster.exe --version
          file dvdisaster.exe
          if ./dvdisaster.exe --version | grep dirty; then exit 1; fi
          file dvdisaster.exe | grep -q 'x86-64'
          file dvdisaster.exe | grep -q 'for MS Windows'
          ./dvdisaster.exe --version | grep "dvdisaster Light"
    - name: try to prepare dist
      run: ./.github/workflows/make-dist.sh ${{ github.ref }}
    - name: run regression tests
      if: matrix.printf == 'normal'
      env:
        REGTEST_NO_UTF8: 1
        MAX_JOBS: 4
      run: |
        mkdir -p /var/tmp/regtest
        echo "Number of available processors: $(nproc || echo U)"
        ./regtest/runtests.sh

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        printf: [fmtdbg, normal]
        include:
          - printf: fmtdbg
            debugprintf: --with-debug-printf-format
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: install prerequisites
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev man jq
    - name: configure
      run: ./configure ${{ matrix.debugprintf }} --with-werror
    - name: make
      run: nproc && make -j$(nproc)
    - name: check executable
      run: |
          ./dvdisaster --version
          ./dvdisaster --version | grep "dvdisaster Light"
    - name: prepare dist
      run: ./.github/workflows/make-dist.sh ${{ github.ref }}
    - name: regression tests
      if: matrix.printf == 'normal'
      env:
        REGTEST_NO_UTF8: 1
        MAX_JOBS: 4
      run: |
        mkdir -p /var/tmp/regtest
        echo "Number of available processors: $(nproc || echo U)"
        ./regtest/runtests.sh
